-- rustgroup.newGroup!
-- rustgroup.newGroup!
-- rustgroup.newGroup!
-- 
-- rustgroup.printGroups!
-- print "------------------ 1 ---------------------"
-- 
-- rustgroup.remGroup 1
-- 
-- rustgroup.printGroups!
-- print "------------------ 2 ---------------------"
